index.html
This is a long running PR that we need to pull in from @AxelNennker.
=> Fix JSON-LD context first line requirement.

index.html, ld-keys.html
This PR splits the key descriptions out of the main DID spec.
=> Move standard key descriptions to separate specification.

did-methods.html, index.html
This PR splits the DID Method Registry out from the specification.
=> Split DID Method Registry out of specification.

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/peacekeeper/did-spec/pull/43.html" title="Last updated on Jan 22, 2018, 9:02 AM GMT (698577a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/43/c6db2cb...peacekeeper:698577a.html" title="Last updated on Jan 22, 2018, 9:02 AM GMT (698577a)">Diff</a>
=> Update data model and examples for service endpoints.

index.html
a couple of references were outdated due to the removal of sections. some examples were outdated and didn't match the specification.
***
<a href="https://pr-preview.s3.amazonaws.com/zoellner/did-spec/pull/48.html" title="Last updated on Feb 6, 2018, 6:44 PM GMT (eda9a2d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/48/4e6c77c...zoellner:eda9a2d.html" title="Last updated on Feb 6, 2018, 6:44 PM GMT (eda9a2d)">Diff</a>
=> fix references and examples

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/peacekeeper/did-spec/pull/50.html" title="Last updated on Feb 25, 2018, 8:33 AM GMT (c5f1528)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/50/1e0ecb5...peacekeeper:c5f1528.html" title="Last updated on Feb 25, 2018, 8:33 AM GMT (c5f1528)">Diff</a>
=>  Add 'Public Keys' section and update 'Authentication' section.

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/67.html" title="Last updated on Mar 13, 2018, 2:23 PM GMT (b2b8758)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/67/b0f2168...b2b8758.html" title="Last updated on Mar 13, 2018, 2:23 PM GMT (b2b8758)">Diff</a>
=> Note that DID Methods need to specify authn/guardianship. Fixes #13.

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/68.html" title="Last updated on Mar 13, 2018, 2:23 PM GMT (f972264)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/68/b0f2168...f972264.html" title="Last updated on Mar 13, 2018, 2:23 PM GMT (f972264)">Diff</a>
=> Clarify that DID Documents may have intermediate forms. Fixes #18.

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/69.html" title="Last updated on Apr 2, 2018, 8:35 PM GMT (c58df5c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/69/b0f2168...c58df5c.html" title="Last updated on Apr 2, 2018, 8:35 PM GMT (c58df5c)">Diff</a>
=> Add note of owner field and underlying specifications. Fixes #25.

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/79.html" title="Last updated on May 15, 2018, 2:08 PM GMT (34dd3ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/79/8f2bd19...34dd3ba.html" title="Last updated on May 15, 2018, 2:08 PM GMT (34dd3ba)">Diff</a>
=> Add key search algorithm as requested by @mikelodder7. Fixes #51.

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/76.html" title="Last updated on May 12, 2018, 3:08 PM GMT (ff3a4aa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/76/5f20c5d...ff3a4aa.html" title="Last updated on May 12, 2018, 3:08 PM GMT (ff3a4aa)">Diff</a>
=> Fix privacy issues by removing biometric templates. Fixes #62.

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/75.html" title="Last updated on May 27, 2018, 5:51 PM GMT (e73f197)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/75/5f20c5d...e73f197.html" title="Last updated on May 27, 2018, 5:51 PM GMT (e73f197)">Diff</a>
=> Propose service endpoint identification mechanism. Fixes #72.

common.js, index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/78.html" title="Last updated on May 15, 2018, 1:55 PM GMT (ecf73c6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/78/8f2bd19...ecf73c6.html" title="Last updated on May 15, 2018, 1:55 PM GMT (ecf73c6)">Diff</a>
=> Add section on extensibility. Fixes #58.

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/canadaduane/did-spec/pull/88.html" title="Last updated on May 31, 2018, 4:47 PM GMT (2bb0eed)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/88/e55832a...canadaduane:2bb0eed.html" title="Last updated on May 31, 2018, 4:47 PM GMT (2bb0eed)">Diff</a>
=> Fix typos and some grammar

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/91.html" title="Last updated on Jun 25, 2018, 1:20 PM GMT (1f49fee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/91/f6ebf04...1f49fee.html" title="Last updated on Jun 25, 2018, 1:20 PM GMT (1f49fee)">Diff</a>
=> Added signature text to address issue 42

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/93.html" title="Last updated on Jul 2, 2018, 5:03 PM GMT (879b73d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/93/5e758f2...879b73d.html" title="Last updated on Jul 2, 2018, 5:03 PM GMT (879b73d)">Diff</a>
=> Address Issue 63

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/did-spec/pull/94.html" title="Last updated on Jul 23, 2018, 3:48 PM GMT (7ee3f98)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/94/6c50ae4...TallTed:7ee3f98.html" title="Last updated on Jul 23, 2018, 3:48 PM GMT (7ee3f98)">Diff</a>
=> minor punctuation and grammar fixes

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/dhh1128/did-spec/pull/99.html" title="Last updated on Aug 23, 2018, 2:06 AM GMT (7b02904)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/99/6c50ae4...dhh1128:7b02904.html" title="Last updated on Aug 23, 2018, 2:06 AM GMT (7b02904)">Diff</a>
=> do not recommend unique pairwise endpoints

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/TalAter/did-spec/pull/111.html" title="Last updated on Oct 31, 2018, 1:31 PM GMT (a231ecc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/111/4b0d5e9...TalAter:a231ecc.html" title="Last updated on Oct 31, 2018, 1:31 PM GMT (a231ecc)">Diff</a>
=> Fixed capitalization of DID

index.html, terms.html
From https://github.com/w3c-ccg/did-spec/pull/107 plus requested changes.
(Addresses https://github.com/w3c-ccg/did-spec/issues/86)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/161.html" title="Last updated on Jan 25, 2019, 9:05 PM UTC (ab96cfc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/161/6c50ae4...ab96cfc.html" title="Last updated on Jan 25, 2019, 9:05 PM UTC (ab96cfc)">Diff</a>
=> JSON Pointer issue 86

index.html, terms.html
This PR only touches *structure*. There are still (editorial) *content* related issues that will be addressed in a future PR if this starting point is okay.
* Moved the URIs/URNs/URLs section into Terminology - for the time being at least. This needs more work, content-wise, and depending on that may get moved again. (#155, #156, #159)
* Made a top level DID Methods section, which now contains DID Method Schema and DID Operations (#151).
* TODO: there's language about DID Methods in Persistence, in the DIDs section, which might need adjusting out into the DID Methods section, but it's pretty tightly bound up so leaving that for a future PR.
* Bumped Purpose and Simple Examples up a level, which based on the `h`s they used to be anyway, so I think this might have been a section nesting …
=> Initial refactor

index.html, terms.html
with @msporny at RWOT8
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/173.html" title="Last updated on Mar 2, 2019, 5:28 PM UTC (0f5eeb6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/173/aeb7bc6...0f5eeb6.html" title="Last updated on Mar 2, 2019, 5:28 PM UTC (0f5eeb6)">Diff</a>
=> Editorial and structure 

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/181.html" title="Last updated on Mar 28, 2019, 1:47 AM UTC (82ac441)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/181/61ccb7d...82ac441.html" title="Last updated on Mar 28, 2019, 1:47 AM UTC (82ac441)">Diff</a>
=> Clean up terminology section.

common.js, index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/180.html" title="Last updated on Mar 28, 2019, 1:40 AM UTC (defc962)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/180/61ccb7d...defc962.html" title="Last updated on Mar 28, 2019, 1:40 AM UTC (defc962)">Diff</a>
=> Restructure and simplify intro to remove stuff in DID Primer. 

index.html
https://github.com/w3c-ccg/meetings/tree/gh-pages/2019-02-19
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/188.html" title="Last updated on Apr 23, 2019, 8:31 PM UTC (674599b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/188/ce1130d...674599b.html" title="Last updated on Apr 23, 2019, 8:31 PM UTC (674599b)">Diff</a>
=> Announced on 2019-02-19 CCG call as 3rd editor

terms.html
=> Fix characters in DID URL related terminology section.

index.html
Adds examples for sections
- 4.5 Path
- 4.6 Query
- 4.7 Fragment
Address issue: https://github.com/w3c-ccg/did-spec/issues/222
***
<a href="https://pr-preview.s3.amazonaws.com/aljones15/did-spec/pull/225.html" title="Last updated on Jun 15, 2019, 7:14 AM UTC (bd4861c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/225/c3fe67a...aljones15:bd4861c.html" title="Last updated on Jun 15, 2019, 7:14 AM UTC (bd4861c)">Diff</a>
=> Add examples for path, query, and fragment.

index.html
Fixes #203
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/226.html" title="Last updated on Jun 14, 2019, 4:23 AM UTC (30dd3d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/226/a17d86b...30dd3d7.html" title="Last updated on Jun 14, 2019, 4:23 AM UTC (30dd3d7)">Diff</a>
=> Shorter subtitle

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/digitalbazaar/did-spec/pull/236.html" title="Last updated on Jul 9, 2019, 10:32 PM UTC (6e41daf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/236/ddea01a...digitalbazaar:6e41daf.html" title="Last updated on Jul 9, 2019, 10:32 PM UTC (6e41daf)">Diff</a>
=> Style and link cleanups.

index.html
Updates https://github.com/w3c-ccg/did-spec/pull/240 with suggested typo fixes
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/244.html" title="Last updated on Aug 2, 2019, 6:25 PM UTC (8ac136b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/244/72890d6...8ac136b.html" title="Last updated on Aug 2, 2019, 6:25 PM UTC (8ac136b)">Diff</a>
=> Immutability in Sec Con section

index.html
per https://github.com/w3c-ccg/did-wg-charter/pull/58
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/234.html" title="Last updated on Aug 8, 2019, 8:20 PM UTC (e0e68d0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/234/31ae2ee...e0e68d0.html" title="Last updated on Aug 8, 2019, 8:20 PM UTC (e0e68d0)">Diff</a>
=> added section on interop

index.html, terms.html
This was decided during the [2019-08-01 DID Spec and DID Resolution Spec Weekly Meeting](https://github.com/w3c-ccg/meetings/tree/gh-pages/2019-08-01-did-spec-and-resolution).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/250.html" title="Last updated on Aug 3, 2019, 8:37 PM UTC (5da0791)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/250/3492d63...5da0791.html" title="Last updated on Aug 3, 2019, 8:37 PM UTC (5da0791)">Diff</a>
=> Change "Decentralized Identifier Registry" to "DID Registry".

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/did-spec/pull/251.html" title="Last updated on Aug 5, 2019, 4:34 PM UTC (6f26699)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/251/3492d63...TallTed:6f26699.html" title="Last updated on Aug 5, 2019, 4:34 PM UTC (6f26699)">Diff</a>
=> (editorial) punctuation and whitespace tidy-up

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/dhh1128/did-spec/pull/254.html" title="Last updated on Aug 8, 2019, 4:54 PM UTC (4c1e4ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/254/bd4f2fa...dhh1128:4c1e4ba.html" title="Last updated on Aug 8, 2019, 4:54 PM UTC (4c1e4ba)">Diff</a>
=> Clarify intent in section on persistence

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/dhh1128/did-spec/pull/253.html" title="Last updated on Aug 8, 2019, 8:39 PM UTC (5336815)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/253/369544d...dhh1128:5336815.html" title="Last updated on Aug 8, 2019, 8:39 PM UTC (5336815)">Diff</a>
=> clarify second MUST in 4.7 Fragment

common.js, index.html
Fixes #252.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/258.html" title="Last updated on Aug 8, 2019, 3:00 PM UTC (7286440)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/258/bd4f2fa...7286440.html" title="Last updated on Aug 8, 2019, 3:00 PM UTC (7286440)">Diff</a>
=> Reference DID Resolution spec.

index.html
Some minor rewordings, addressing issues #220, #219, #216, #217 and #119.
Please review these to make sure they're accurate in case the meaning was changed to something that's not right. I did each in separate commits so we can pick the ones that are accurate in case they aren't all okay.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/260.html" title="Last updated on Aug 8, 2019, 9:03 PM UTC (595d4f7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/260/fa1dc67...595d4f7.html" title="Last updated on Aug 8, 2019, 9:03 PM UTC (595d4f7)">Diff</a>
=> Editorial updates to intro mostly

index.html, terms.html
Followup from #255
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/261.html" title="Last updated on Aug 8, 2019, 9:15 PM UTC (fcb5941)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/261/aa760d9...fcb5941.html" title="Last updated on Aug 8, 2019, 9:15 PM UTC (fcb5941)">Diff</a>
=> Correct description of DID Subject and add dfn

index.html, terms.html
First pass, trying not to define DID controller using the word "controls"
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/262.html" title="Last updated on Aug 8, 2019, 9:32 PM UTC (0ab6d11)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/262/38f5c6b...0ab6d11.html" title="Last updated on Aug 8, 2019, 9:32 PM UTC (0ab6d11)">Diff</a>
=> Attempt dfn of DID Controller

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/did-spec/pull/264.html" title="Last updated on Aug 9, 2019, 8:56 PM UTC (11276c7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/264/7f80eba...TallTed:11276c7.html" title="Last updated on Aug 9, 2019, 8:56 PM UTC (11276c7)">Diff</a>
=> change — characters to &mdash; entities
