w3c-ccg/did-spec

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/peacekeeper/did-spec/pull/47.html" title="Last updated on Feb 1, 2018, 11:57 AM GMT (81d4a1f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/47/684e5f8...peacekeeper:81d4a1f.html" title="Last updated on Feb 1, 2018, 11:57 AM GMT (81d4a1f)">Diff</a>

Fix 'serviceEndpoint' property name.

---

index.html

This seems to be more a restriction of implementations rather than a requirement for this spec.
JSON does not guarantee the order of fields. DID-spec could only require that context is the first line of a serialization.
Axel
This was discussed month ago and merged but now this issue is back. Why?
***
<a href="https://pr-preview.s3.amazonaws.com/AxelNennker/did-spec/pull/59.html" title="Last updated on Mar 8, 2018, 4:24 PM GMT (8109a9e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/59/8ea8c86...AxelNennker:8109a9e.html" title="Last updated on Mar 8, 2018, 4:24 PM GMT (8109a9e)">Diff</a>

Remove requirement that context must be the first line

---

ietf-registration.txt

This is a complete registration template for IETF registration. I've already submitted it to IETF as a provisional registration, which means we can update it as the spec matures.

Added IETF registration of DID URI Scheme. Fixes #73.

---

index.html

@dmitrizagidulin and I were wondering about this while working on https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-spring2018/blob/master/draft-documents/did_auth_draft.md. OpenID Connect version is 1.0.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/89.html" title="Last updated on Jun 10, 2018, 6:50 AM GMT (c689c27)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/89/f6ebf04...c689c27.html" title="Last updated on Jun 10, 2018, 6:50 AM GMT (c689c27)">Diff</a>

Example OpenID Connect version 1.0 instead of 3.1.

---

index.html

If I receive a message that supposedly originated from X three months ago, verifying that the key for X has not expired today is not helpful; what I need to know is whether it had expired three months ago.
Also, I tried to clarify what implementation (the resolvers) should be compatible with extending-an-expired-key semantics.
***
<a href="https://pr-preview.s3.amazonaws.com/dhh1128/did-spec/pull/98.html" title="Last updated on Aug 23, 2018, 1:47 AM GMT (432c905)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/98/6c50ae4...dhh1128:432c905.html" title="Last updated on Aug 23, 2018, 1:47 AM GMT (432c905)">Diff</a>

Clarify expiration semantics

---

index.html

Resolves https://github.com/w3c-ccg/did-spec/issues/108
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/109.html" title="Last updated on Oct 12, 2018, 6:47 PM GMT (b488077)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/109/4b0d5e9...b488077.html" title="Last updated on Oct 12, 2018, 6:47 PM GMT (b488077)">Diff</a>

removed confusing section about keys and DID ownership

---

index.html

In addressing #101, it was clear that ownership and owner were used throughout despite the problems cited in the issue: namely that proof of control does not establish ownership, just control.
This PR adjusts the language from owner to controller for better accuracy and understandability, both in the spec-text and in the field name.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/102.html" title="Last updated on Sep 15, 2018, 1:23 AM GMT (60ce842)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/102/4b0d5e9...60ce842.html" title="Last updated on Sep 15, 2018, 1:23 AM GMT (60ce842)">Diff</a>

Replace "owner" with "controller"

---

index.html

Cherry picks from https://github.com/w3c-ccg/did-spec/pull/61 to incorporate feedback in the discussion. 
Ready to merge now, but I have an additional proposal to clarify the "vague" text around value properties (https://github.com/w3c-ccg/did-spec/pull/61#discussion_r178646041), which is to move anything around key formats to 5., ie:
> 3. Each public key MUST include `id` and `type` properties.
> 4. ...
> 5. Each public key MUST contain exactly one key with a value of one of: `publicKeyPem`, `publicKeyJwk`, `publicKeyHex`, `publicKeyBase64`, `publicKeyBase58`, or similar depending on the format and encoding of the public key. The array of public keys SHOULD NOT contain duplicate entries with the same `id` and different formats.
***
<a …

Clarify PubKey section

---

index.html

I'm no longer with Blockstream, so changed affiliation before community draft is final.
***
<a href="https://pr-preview.s3.amazonaws.com/ChristopherA/did-spec/pull/178.html" title="Last updated on Mar 27, 2019, 8:26 PM UTC (e144647)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/178/21bcea3...ChristopherA:e144647.html" title="Last updated on Mar 27, 2019, 8:26 PM UTC (e144647)">Diff</a>

Changed my company affiliation and URL in Authors

---

common.js
index.html
terms.html

Use 'Decentralized Identifier Registry' (a type of Verifiable Data Registry) instead of "target system", "ledger" and "distributed ledger". Some references to "distributed ledger" remain but not in direct reference to DIDs, just in explanatory text.
(DIR was discussed at RWOT8.)
This should address #119, #149 and #150
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/184.html" title="Last updated on Mar 31, 2019, 2:49 PM UTC (980fdbc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/184/da1f220...980fdbc.html" title="Last updated on Mar 31, 2019, 2:49 PM UTC (980fdbc)">Diff</a>

Add dfn of Decentralized Identifer Registry

---

common.js
index.html
terms.html

This updates the ABNF and introduces matrix parameters, based on discussions on the mailing list as well as the [DID Spec and DID Resolution Spec Weekly Meetings](https://docs.google.com/document/d/1qYBaXQMUoB86Alquu7WBtWOxsS8SMhp1fioYKEGCabE/) and the resulting [Proposal for Revisions to Decentralized Identifiers Section of DID Spec](https://docs.google.com/document/d/1qnDExIVjU5bYc601qUdLZIi9UAs1ojlHyKnVoz2zlLM/).
**This is a new PR that replaces the earlier https://github.com/w3c-ccg/did-spec/pull/187. In this new one, only the matrix parameter concept itself is introduced, but concrete matrix parameters will be proposed and discussed in separate PRs.**
Separate PRs for concrete matrix parameters: https://github.com/w3c-ccg/did-spec/pull/190, …

Update ABNF to use matrix parameters (new)

---

index.html

This adds one concrete DID URL matrix parameter. See https://github.com/w3c-ccg/did-spec/pull/189.
Description: Identifies a service from the DID Document by service id.
Example: `did:example:1234;service=myhub`
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/190.html" title="Last updated on May 10, 2019, 11:38 AM UTC (ddec242)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/190/fde9370...ddec242.html" title="Last updated on May 10, 2019, 11:38 AM UTC (ddec242)">Diff</a>

Add "service" DID URL matrix parameter.

---

index.html

A starting point; I expect people will have lots of opinions about what goes in here.
The **Unique DID Method Names** section tries to strike a balance between explaining why the DID Method Registry is useful, without implying it's authoritative or required, and without being too defensive about its existence at all.
@talltree's original proposal was to call it "Governance of DID Method Namespaces" but I thought "governance" implied a bit more authority or even just process than perhaps we want to associate with the DID Method Registry. 
Also there might be a better place in the spec for this section.
I also added a *very short* section in Security Considerations because if I understand correctly potential non-unique DID method names could be an attack vector. This might warrant expanding …

Add non-normative section about the DID Method Registry, re: #133

---

index.html

This PR addresses the immediate need to support public keys as Ethereum addresses and removes constraints on public keys in general. This will ensure that any entry in the referenced registry (once final) can be used to describe the key types and formats.
***
<a href="https://pr-preview.s3.amazonaws.com/uport-project/did-spec/pull/202.html" title="Last updated on Jun 6, 2019, 6:35 PM UTC (3786800)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/202/fde9370...uport-project:3786800.html" title="Last updated on Jun 6, 2019, 6:35 PM UTC (3786800)">Diff</a>

Fix #201 and #56 -- Added support for public keys as Ethereum addresses 

---

contexts/did-v0.11.jsonld

sec:EcdsaSecp256k1Signature2019, sec:SchnorrSecp256k1Signature2019, sec:Secp256k1VerificationKey2018

Add secp256k to context (did-v0.11.jsonld).

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/242.html" title="Last updated on Aug 1, 2019, 8:20 PM UTC (f9e9959)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/242/7b2cf89...f9e9959.html" title="Last updated on Aug 1, 2019, 8:20 PM UTC (f9e9959)">Diff</a>

Add `controller` pattern example (also replaces Guardianship).

---

index.html

This PR moves proposed text from the [DID WG charter ](https://github.com/w3c-ccg/did-wg-charter/pull/41) to the DID specification.
Signed-off-by: Brent <brent.zundel@gmail.com>
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/did-spec/pull/239.html" title="Last updated on Jul 15, 2019, 7:39 PM UTC (f11a38d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/239/f3c7dae...brentzundel:f11a38d.html" title="Last updated on Jul 15, 2019, 7:39 PM UTC (f11a38d)">Diff</a>

moved list from charter to spec

---

common.js
index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/208.html" title="Last updated on Jun 3, 2019, 1:20 PM UTC (1a3c05b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/208/e268a4e...1a3c05b.html" title="Last updated on Jun 3, 2019, 1:20 PM UTC (1a3c05b)">Diff</a>

Add link to spec for discovering DIDs from DNS.

---

index.html

According to later in the spec, attribute 'id' is a required field of a 'service' definition.
Have come across uPort docs that do not specify **authentication** and **'service'**s with the **id** attributes and perhaps this incomplete example may mislead devs.
***
<a href="https://pr-preview.s3.amazonaws.com/DibbsZA/did-spec/pull/206.html" title="Last updated on Jun 3, 2019, 8:11 AM UTC (9bb2c77)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/206/e268a4e...DibbsZA:9bb2c77.html" title="Last updated on Jun 3, 2019, 8:11 AM UTC (9bb2c77)">Diff</a>

Added 'id' attribute of the 'service' definition for DID doc example

---

index.html
terms.html

There are several cases in the spec where keywords from [RFC2119](http://www.rfc-editor.org/rfc/rfc2119.txt) _might_ not be capitalized.
***
<a href="https://pr-preview.s3.amazonaws.com/aljones15/did-spec/pull/209.html" title="Last updated on Aug 1, 2019, 7:31 PM UTC (8f8ff99)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/209/c3fe67a...aljones15:8f8ff99.html" title="Last updated on Aug 1, 2019, 7:31 PM UTC (8f8ff99)">Diff</a>

Capitalize specification requirements.

---

index.html

Fixes typo in https://github.com/w3c-ccg/did-spec/pull/230
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/245.html" title="Last updated on Aug 2, 2019, 6:35 PM UTC (a64df96)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/245/9dc12be...a64df96.html" title="Last updated on Aug 2, 2019, 6:35 PM UTC (a64df96)">Diff</a>

Add correct Identity Hub ServiceEndpoint format

---

index.html

Similar to the ones that have been merged in https://github.com/w3c-ccg/did-spec/pull/209
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/248.html" title="Last updated on Aug 2, 2019, 9:46 PM UTC (ab9a1b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/248/957ef13...ab9a1b6.html" title="Last updated on Aug 2, 2019, 9:46 PM UTC (ab9a1b6)">Diff</a>

Another RFC2119 capitalization fix

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/179.html" title="Last updated on Aug 6, 2019, 4:53 PM UTC (0d7bfd0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/179/3492d63...0d7bfd0.html" title="Last updated on Aug 6, 2019, 4:53 PM UTC (0d7bfd0)">Diff</a>

Update abstract to build bigger tent / weaken "decentralization" requirement

---

index.html

Changes examples only, fixes #241
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/246.html" title="Last updated on Aug 2, 2019, 6:50 PM UTC (543deed)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/246/957ef13...543deed.html" title="Last updated on Aug 2, 2019, 6:50 PM UTC (543deed)">Diff</a>

Replace draft context URI with w3.org one in all examples

---

index.html

Fixes internal section references in "Proof" section. Mentions "controller" now that https://github.com/w3c-ccg/did-spec/pull/242/ has been merged. Replaces https://github.com/w3c-ccg/did-spec/pull/237/.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/249.html" title="Last updated on Aug 3, 2019, 8:24 PM UTC (4dd52f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/249/3492d63...4dd52f1.html" title="Last updated on Aug 3, 2019, 8:24 PM UTC (4dd52f1)">Diff</a>

Fix references in "Proof" section.

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/dhh1128/did-spec/pull/255.html" title="Last updated on Aug 8, 2019, 9:38 AM UTC (8d99ae0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/255/bd4f2fa...dhh1128:8d99ae0.html" title="Last updated on Aug 8, 2019, 9:38 AM UTC (8d99ae0)">Diff</a>

Fix inconsistent use of term 'DID subject'

---

index.html

Fixes #221
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/259.html" title="Last updated on Aug 8, 2019, 8:55 PM UTC (ef9fd1b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/259/6a69615...ef9fd1b.html" title="Last updated on Aug 8, 2019, 8:55 PM UTC (ef9fd1b)">Diff</a>

Add magic css so comments in examples aren't selected

---

index.html

The data model section is empty, so I added basic information under each heading with the expectation that it'll be filled out with more detail and probably diagrams at a later date. But at least it's not empty any more. I tried to avoid any controversial language and keep it simple in the hopes that this doesn't generate too much discussion at this late stage.
ALTERNATIVE PR: https://github.com/w3c-ccg/did-spec/pull/256 which removes the data model section entirely. Use this if the contents of this PR are going to be too controversial to merge fast.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/pull/257.html" title="Last updated on Aug 8, 2019, 9:22 PM UTC (b984d61)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/257/c9640fd...b984d61.html" …

Add basic info to the data model section

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/peacekeeper/did-spec/pull/265.html" title="Last updated on Aug 10, 2019, 5:32 PM UTC (67ae5a1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/265/0b1a796...peacekeeper:67ae5a1.html" title="Last updated on Aug 10, 2019, 5:32 PM UTC (67ae5a1)">Diff</a>

change case to "DID Document" everywhere
